"""add_default_for_avatar

Revision ID: f0b7a1d9d22a
Revises: e97337a6fc77
Create Date: 2024-04-28 22:34:38.822964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b7a1d9d22a'
down_revision: Union[str, None] = 'e97337a6fc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
